### POST request to save patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Bob Brown",
  "email": "bob.brown@example.com",
  "address": "321 Pine St, Springfield",
  "dateOfBirth": "1982-11-30",
  "registeredDate": "2023-05-14"
}

###