### UPDATE request
PUT http://localhost:4000/patients/04632343-5283-41a1-a8b0-4118508be624
Content-Type: application/json

{
  "name": "John Doe",
  "address": "123, main street",
  "dateOfBirth": "1995-09-09"
}

###